* Pauls Matlab Functions

A bunch of useful functions I've written. I'll add them slowly, as I document and create tests for them. Most of them should work with scalars or vectors. Some may work with matrices (if it makes sense). I have these in a folder added to my matlab path.

** Financial
    These functions are quick to calculate loan and investment payments. They all assume an annualised 
    rate, compounded monthly and the periods expressed in months.
    - PMT - Loan payment calculator.
    - FV - Future value, or the total amount of a loan you pay including interest.
    - FVpayment - Future value of a fixed monthly payment.
    - PV - Present value, or how much you need to invest now.
** Utilities
    - s - Show a number [vector or matrix]. Does matlab drive you crazy having to fprintf everything, just use `s'.
    - columns_in - Tells you how many decimals before the point.
** Examples
>> s([amounts; PMT(amounts,2.5/7,48); PMT(amounts, 2.57,60); PMT(amounts, 2.57,120)], 0)
|  80000 |  90000 | 100000 | 110000 | 120000 | 130000 | 140000 | 150000 |
|   1679 |   1889 |   2099 |   2308 |   2518 |   2728 |   2938 |   3148 |
|   1422 |   1600 |   1778 |   1956 |   2133 |   2311 |   2489 |   2667 |
|    757 |    851 |    946 |   1040 |   1135 |   1230 |   1324 |   1419 |

>> s([amounts' PMT(amounts,2.57,48)' PMT(amounts, 2.57,60)' PMT(amounts, 2.57,120)'], 0)
|  80000 |   1756 |   1422 |    757 |
|  90000 |   1975 |   1600 |    851 |
| 100000 |   2194 |   1778 |    946 |
| 110000 |   2414 |   1956 |   1040 |
| 120000 |   2633 |   2133 |   1135 |
| 130000 |   2853 |   2311 |   1230 |
| 140000 |   3072 |   2489 |   1324 |
| 150000 |   3292 |   2667 |   1419 |
